matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
  - os: osx
    osx_image: xcode8.1
language: c++
install:
- mkdir $TRAVIS_BUILD_DIR/logs
- touch $TRAVIS_BUILD_DIR/logs/build_logs
- BUILDLOGS=$TRAVIS_BUILD_DIR/logs/build_logs
- cd $TRAVIS_BUILD_DIR
- echo "***************************** Building externals ****" > $BUILDLOGS
- cd $TRAVIS_BUILD_DIR/examples/pxScene2d/external
- ./build.sh>>$BUILDLOGS
script:
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh ./build_linux.sh; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sh ./build_osx.sh; fi
- tar -cvzf logs.tgz logs/*
addons:
  ssh_known_hosts: 96.118.6.151
after_script:
- cd $TRAVIS_BUILD_DIR
- ./deploy.sh 96.118.6.151 logs.tgz
- rm -rf /tmp/pxscene-build.pem
before_install:
- openssl aes-256-cbc -K $encrypted_8b763c087de9_key -iv $encrypted_8b763c087de9_iv
  -in pxscene-build.pem.enc -out /tmp/pxscene-build.pem -d
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git libglew-dev freeglut3 freeglut3-dev libgcrypt11-dev zlib1g-dev g++ libssl-dev nasm autoconf; fi
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/pxscene-build.pem
- ssh-add /tmp/pxscene-build.pem
